name: Run Newman Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Newman and HTML Extra Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Postman Collection and Generate Reports
        run: |
          newman run "Day 5_Writing Basic Assertions.postman_test_run.json" \
            -r htmlextra,json \
            --reporter-json-export results.json \
            --reporter-htmlextra-export report.html

      - name: Upload JSON Report
        uses: actions/upload-artifact@v3
        with:
          name: newman-json-results
          path: results.json

      - name: Upload HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: newman-html-report
          path: report.html
